name: sample
description: "Spurr SDK Sample App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  spurr:
    path: ../sdk

flutter:
  uses-material-design: true
